PalletTown_PlayersHouse_2F_Text_PlayedWithNES:: @ 818D50B
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp:: @ 818D53B
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_StarterSeason_Mom1::
    .string "MOM: {PLAYER}!\n"
    .string "I'm so proud you graduated in…\p"
    .string "…Erm, when was that?$"

PalletTown_PlayersHouse_2F_Text_StarterSeason_Mom2::
    .string "Of course, last {STR_VAR_1}!\n"
    .string "I heard wild Pokémon change between\p"
    .string "seasons… so be careful! After a\n"
    .string "full year, I'm sure you will\p"
    .string "be a great Trainer!\n"
    .string "Here, this will help you.$"

PalletTown_PlayersHouse_2F_Text_StarterSeason_Mom3::
    .string "Farewell, and promise me\n"
    .string "you will never forget MOM.$"
