
EventScript_RoamersPhoneCall_Text_Route1::
    .string "ROUTE1$"

EventScript_RoamersPhoneCall_Text_Route2::
    .string "ROUTE2$"

EventScript_RoamersPhoneCall_Text_Route3::
    .string "ROUTE3$"

EventScript_RoamersPhoneCall_Text_Route4::
    .string "ROUTE4$"

EventScript_RoamersPhoneCall_Text_Route5::
    .string "ROUTE5$"

EventScript_RoamersPhoneCall_Text_Route6::
    .string "ROUTE6$"

EventScript_RoamersPhoneCall_Text_Route7::
    .string "ROUTE7$"

EventScript_RoamersPhoneCall_Text_Route8::
    .string "ROUTE8$"

EventScript_RoamersPhoneCall_Text_Route9::
    .string "ROUTE9$"

EventScript_RoamersPhoneCall_Text_Route10::
    .string "ROUTE10$"

EventScript_RoamersPhoneCall_Text_Route11::
    .string "ROUTE11$"

EventScript_RoamersPhoneCall_Text_Route12::
    .string "ROUTE12$"

EventScript_RoamersPhoneCall_Text_Route16::
    .string "ROUTE16$"

EventScript_RoamersPhoneCall_Text_Route21North::
    .string "ROUTE21 NORTH$"

EventScript_RoamersPhoneCall_Text_Route22::
    .string "ROUTE22$"

EventScript_RoamersPhoneCall_Text_Route24::
    .string "ROUTE24$"

EventScript_RoamersPhoneCall_Text_Raikou::
    .string "RAIKOU$"

EventScript_RoamersPhoneCall_Text_Suicune::
    .string "SUICUNE$"

EventScript_RoamersPhoneCall_Text_Entei::
    .string "ENTEI$"

EventScript_RoamersPhoneCall_Text_Find1stLegendary::
    .string "{PLAYER}, it's Professor Oak.\n"
    .string "Yes, you can use Pokédex as a\p" 
    .string "receiver phone. Huh? I never told\n" 
    .string "you? Anyway, we don't have time\p"
    .string "for this. This is an emergency!\n"
    .string "{STR_VAR_1}, the Legendary Roamer\p"
    .string "Pokémon, is rampaging {STR_VAR_2}.\n"
    .string "He's so strong that I'm afraid only\p"
    .string "YOU would be able to stop him.\n"
    .string "After you do, I'll upgrade your\p"
    .string "Pokédex to a fully useful PHONE!\n"
    .string "Please Hurry! Bye!$"

EventScript_RoamersPhoneCall_Text_Find2ndLegendary::
    .string "{PLAYER}, it's Professor Oak.\n"
    .string "This is an emergency!\p"
    .string "My theory was right: All three\n"
    .string "Legendary Roamers Pokémon are\p"
    .string "rampaging in random locations.\n"
    .string "{STR_VAR_1} is in {STR_VAR_2}\p"
    .string "Once again, YOU have to stop this.\n"
    .string "Please hurry! Bye!$"

EventScript_RoamersPhoneCall_Text_Find3rdLegendary::
    .string "{PLAYER}, it's Professor Oak.\n"
    .string "This is an emergency!\p"
    .string "We found {STR_VAR_1}, the last\n"
    .string "Legendary Roamer Pokémon.\p"
    .string "He is in {STR_VAR_2}.\n"
    .string "Be careful, I heard he's somehow\p"
    .string "stronger than the other two.\p"
    .string "Please hurry! Bye!$"
